name: Release

permissions:
  contents: write

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  create-release:
    name: create-release
    runs-on: ubuntu-22.04
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
    steps:
      - name: Create GitHub release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: true

  build-and-upload:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust
      run: rustup update stable && rustup default stable
    
    - name: Create Release Archive
      run: |
        cargo install --path=. --locked --root=release

        mkdir crab-0.1.0
        cp release/bin/crab crab-0.1.0/
        cp README.md crab-0.1.0/

        tar czvf crab-0.1.0.tar.gz crab-0.1.0

    - name: Upload release archive
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: crab-0.1.0.tar.gz
        asset_name: crab-0.1.0.tar.gz
        asset_content_type: application/octet-stream